### ISSUE TITLE
way to run without DynamoDB + SNS?

### ISSUE THREAD

**Issue by bman654** [johnagan/serverless-slackbot#2]
What's the purpose of DynamoDB & SNS in:

API Gateway -> Lambda -> DynamoDB -> SNS -> Lambda -> Custom Script

Are you storing all of the messages in DynamoDB?  If our bot doesn't need any memory, can this be simplified to:

API Gateway -> Lambda -> Custom Script

?

**Comment by johnagan** [comment]
haven't looked at this code in years, but pretty sure dynamo is for auth

**Comment by bman654** [comment]
ah this uses OAuth to log the bot in instead of manually configured bot tokens?  Thanks
